fix(rse): include lib-psa to resolve build
Unless platforms include lib/psa into platform specific makefile the
rse_comms throws build error on its own:
  CC      drivers/arm/rse/rse_comms_protocol.c
drivers/arm/rse/rse_comms.c:13:10: fatal error: psa/client.h: No such file or directory
   13 | #include <psa/client.h>

So add PLAT_INCLUDES entry to include the lib/psa to rse_comms.mk.

Signed-off-by: Vivek Gautam <vivek.gautam@arm.com>
Change-Id: I4cbcbbaf20285990239d605f0b3b3dc92bea61e6
(cherry picked from commit 654ae705c35baa1fbd13a0cd8558a64c8454347c)
Reviewed-on: https://gerrit.st.com/c/mpu/oe/st/tf-a/+/443847
ACI: CIBUILD <MDG-smet-aci-builds@list.st.com>
Tested-by: Yann GAUTIER <yann.gautier@foss.st.com>
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>
Reviewed-by: Maxime MERE <maxime.mere@foss.st.com>
Domain-Review: Yann GAUTIER <yann.gautier@foss.st.com>
Reviewed-by: Yann GAUTIER <yann.gautier@foss.st.com>